### ISSUE TITLE
does not work for v4.2.2.stable.official [15073afe3]

### ISSUE THREAD

**Issue by RakibRyan** [Dev-Marco/CCN---Correct-Conventional-Naming-for-Godot-Scripts#1]

**Comment by Dev-Marco** [comment]
Could you explain a little bit more in detail what it is that is not working? As for me it works fine on v4.2.2.stable.official [15073afe3]. Just to be clear you did remember to enable the plugin after installing it?

**Comment by RakibRyan** [comment]
I missed the part that said attach script to a node
